version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: deploy/app.Dockerfile
    restart: always
    volumes:
      - static_volume:/app/static/
    env_file:
      - core/.env
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: deploy/nginx.Dockerfile
    restart: always
    volumes:
      - static_volume:/app/static/
    env_file:
      - core/.env
    expose:
      - "80"
    ports:
      - "8000:80"
    depends_on:
      - app

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - core/.env
    ports:
      - "5433:5432"

volumes:
  static_volume:
  postgres_data:

